# Generated by Django 5.1.1 on 2025-01-28 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
